In [1]:
import numpy as np
import gym


class MazeEnv(gym.Env):
    def __init__(self, point_holes, row, col):
        self.nrow = row
        self.ncol = col
        self.col = 0
        self.row = 0
        self.grids = self.__set_points(point_holes)

    def __set_points(self, point_holes):
        grids = [["F" for _ in range(self.ncol)] for _ in range(self.nrow)]
        grids[self.col][self.row] = "S"   # Set start point
        grids[-1][-1] = "G"  # Set goal point
        for point_hole in point_holes:   # Set hole points
            row, col = point_hole
            grids[row][col] = "H"
        final_grids = ["".join(grid_row) for grid_row in grids]
        return final_grids

    def step(self, action):
        self.transition(action)
        new_state = self.get_state()
        reward = 0
        done = False
        grid = self.grids[self.row][self.col]
        if grid == "H":
            # done = True
            reward = -10
        elif grid == "G":
            done = True   # Stop step when agent come only goal
            reward = 100
        return new_state, reward, done, ""

    def reset(self):
        self.col = 0
        self.row = 0
        return 0

    def transition(self, action):
        if action == 0:    # LEFT
            self.co = max(0, self.col-1)
        elif action == 1:  # DOWN
            self.row = min(self.row+1, self.nrow-1)
        elif action == 2:  # RIGHT
            self.col = min(self.col+1, self.ncol-1)
        elif action == 3:  # UP
            self.row = max(self.row-1, 0)

    def get_state(self):
        return self.row * self.ncol + self.col

In [2]:
def epsilon_greedy(Q, state, action_num, epsilon):
    if np.random.random() < epsilon:
        return np.random.randint(action_num)
    else:
        return np.random.choice(np.where(Q[state, ] == Q[state, ].max())[0])

In [3]:
num_episodes = 1000
alpha = 0.2
gamma = 0.9
epsilon = 0.2
col, row = 5, 5
point_holes = [(0, 3), (1, 1), (2, 1), (2, 3), (3, 3), (4, 1)]
rewards = []
env = MazeEnv(point_holes, col, row)
state_num, action_num = col * row, 4
Q = np.zeros((state_num, action_num))

In [4]:
print("\n".join(env.grids))

SFFHF
FHFFF
FHFHF
FFFHF
FHFFG


In [5]:
for i in range(num_episodes):
    s = env.reset()
    episode_reward = 0
    while True:
        a = epsilon_greedy(Q, s, action_num, epsilon)
        s1, r, d, _ = env.step(a)
        episode_reward += r
        Q[s, a] += alpha * (r + gamma * Q[s1, ].max() - Q[s, a])
        s = s1
        if d:
            break
    rewards.append(episode_reward)
print(rewards[:10], rewards[-10:], sep='\n')  # Show head & tail of rewards

[80, 80, 80, 80, 90, 100, 80, 70, 90, 80]
[100, 100, 100, 100, 90, 100, 100, 100, 100, 100]


In [6]:
action_to_arrow = {
    0: "←",
    1: "↓",
    2: "→",
    3: "↑"
}
for row in range(5):
    for col in range(5):
        print(action_to_arrow[Q[row*5+col, ].argmax()], end="")
    print()

→→↓↓↓
→→→→↓
↓↓↑→↓
→→↑↓↓
←↑→→←


In [7]:
print(np.round(Q.reshape([5, 5, 4]), 2))  # separate by col & row

[[[ 4.305e+01  3.881e+01  4.783e+01  4.305e+01]
  [ 4.783e+01  4.314e+01  5.314e+01  4.783e+01]
  [ 5.314e+01  5.905e+01  4.905e+01  5.314e+01]
  [ 4.150e+01  6.561e+01  4.778e+01  3.243e+01]
  [ 4.066e+01  7.290e+01  4.817e+01  4.053e+01]]

 [[ 1.367e+01  5.900e-01  4.314e+01  0.000e+00]
  [ 1.921e+01  3.900e-01  5.905e+01  2.334e+01]
  [ 5.905e+01  5.311e+01  6.561e+01  5.314e+01]
  [ 6.561e+01  6.290e+01  7.290e+01  4.905e+01]
  [ 7.290e+01  8.100e+01  7.290e+01  6.561e+01]]

 [[ 0.000e+00  2.990e+00 -2.000e+00  0.000e+00]
  [ 0.000e+00  2.157e+01  0.000e+00 -2.000e+00]
  [ 3.126e+01  3.062e+01  1.490e+01  5.905e+01]
  [ 3.112e+01 -3.700e+00  8.100e+01  0.000e+00]
  [ 8.100e+01  9.000e+01  8.100e+01  7.290e+01]]

 [[ 0.000e+00  0.000e+00  1.127e+01  0.000e+00]
  [ 0.000e+00 -3.600e+00  3.844e+01 -4.300e+00]
  [ 3.440e+00  1.580e+00 -2.000e+00  5.195e+01]
  [-1.350e+00  1.959e+01  0.000e+00  0.000e+00]
  [ 9.000e+01  1.000e+02  9.000e+01  8.100e+01]]

 [[ 0.000e+00  0.000e+00 -2.000e